### ISSUE TITLE
CREATE Seed Database

### ISSUE THREAD

**Issue by prodvy** [Diedericovich/ChefByStep#13]
- [x] Create Recipes: **7** (15/06/2021)

- [x] Create Ingredients:

- [x] Create Users?

**Comment by DotEmms** [comment]
Do we make entries for Ingredients and/or users in the DB?

**Comment by JensVanGelder** [comment]
We have entries for ingredients in the db, the api calls for them should work as well, they're not yet been normalized though (lots of duplicates are possible)
We do not yet have any users though
